!title வெற்றியைத் தீர்மானிப்பது கடவுளா? - ஜென் கதைகள்
!cover https://siruvarmalar.b-cdn.net/wp-content/uploads/toss.jpg
!date Sep 15, 2020


!image https://siruvarmalar.b-cdn.net/wp-content/uploads/toss.jpg


இரு நாட்டுப் படைகளுக்கும் இடையே வெகு மும்முரமாக சண்டை நடந்து கொண்டிருந்தது.

எதிரி நாட்டுப் படையிடம் கிட்டத்தட்ட தோற்றுவிட்ட நிலை. ஆனாலும் தாய்நாட்டுப் படைத் தளபதிக்கு போரை இழக்கமாட்டோம் என்ற அசாத்திய நம்பிக்கை. ஆனால் துணைத் தளபதி உள்ளிட்ட அவன் வீரர்களுக்கு அந்த நம்பிக்கை கிஞ்சித்தும் இல்லை. எல்லோரும் ஓடுவதில் குறியாக இருந்தனர்.


!newpage

என்னதான் நம்பிக்கை இருந்தாலும், வீரர்களில்லாம் தனி ஆளாய் என்ன செய்ய முடியும்?

கடைசி நாள் சண்டை. போர்க்களத்துக்குப் போகும் வழியில் ஒரு கோயிலைக் கண்டார்கள்.

உடனே தளபதி வீரர்களை அழைத்து, “சரி வீரர்களே… நாம் ஒரு முடிவுக்கு வருவோம். இதோ இந்தக் கோயிலுக்கு முன் ஒரு நாணயத்தைச் சுண்டிவிடுகிறேன். அதில் தலை விழுந்தால் வெற்றி நமக்கே. பூ விழுந்தால் நாம் தோற்பதாக அர்த்தம். இப்படியே திரும்பிவிடுவோம்…வெற்றியா தோல்வியா.. நமக்கு மேல் உள்ள சக்தி தீர்மானிக்கட்டும்… சரியா?”

“ஆ.. நல்ல யோசனை… அப்படியே செய்வோம்…”


!newpage


நாணயத்தைச் சுண்டினான் தளபதி. காற்றில் மிதந்து, விர்ரென்று சுழன்று தரையில் விழுந்தது நாணயம்.

தலை…!

வீரர்கள் உற்சாகத்தில் மிதந்தனர். வெற்றி வெற்றி என்று எக்காளமிட்டபடி போர்க்களம் நோக்கி ஓடினர். வெகு வேகமாக சண்டையிட்டனர் எதிரி நாட்டவர்களோடு.

அட.. என்ன ஆச்சர்யம். அந்த சிறிய படை, எதிரி நாட்டின் பெரும் படையை வீழ்த்திவிட்டது!


!newpage

துணைத் தளபதி வந்தான். ‘நாம் வென்றுவிட்டோம்… கடவுள் தீர்ப்பை மாற்ற முடியாதல்லவா…” என்றான் உற்சாகத்துடன்.

“ஆமாம்… உண்மைதான்” என்படி அந்த நாணயத்தை துணைத் தளபதியிடம் கொடுத்தான் தளபதி.

நாணயத்தின் இரு பக்கங்களிலும் தலை!

